baseURL: "https://promptlyoffice-gif.github.io/"
title: "Promptly"
defaultContentLanguage: ua
languages:
  ua:
    languageName: "Українська"
    weight: 1
  en:
    languageName: "English"
    weight: 2
theme: "PaperMod"
params:
  comments: true
  giscus:
    repo: "promptlyoffice-gif/promptlyoffice-gif.github.io"
    repoID: ""
    category: "General"
    categoryID: ""
