      - name: Prepare themes directory and clone PaperMod
        run: |
          # Якщо існує файл/не-директорія 'themes' — видаляємо її
          if [ -f themes ]; then
            rm -f themes
          fi
          if [ -e themes ] && [ ! -d themes ]; then
            rm -f themes
          fi
          mkdir -p themes
          git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/papermod

      - name: Patch PaperMod RSS for Hugo compatibility
        run: |
          RSS_FILE="themes/papermod/layouts/_default/rss.xml"
          if [ -f "$RSS_FILE" ]; then
            echo "Patching $RSS_FILE"
            # Заміна .LanguageCode на .Lang (підходить для більшості шаблонів)
            sed -i 's/Site.LanguageCode/Site.Language.Lang/g' "$RSS_FILE" || true
            sed -i 's/\.LanguageCode/\.Lang/g' "$RSS_FILE" || true
            # додаткові захисні заміни (на всякий випадок)
            sed -i 's/\.Language\.LanguageCode/\.Language\.Lang/g' "$RSS_FILE" || true
          else
            echo "$RSS_FILE not found — skipping patch"
          fi
