name: Build and deploy Hugo site to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Prepare themes and clone PaperMod
        run: |
          if [ -f themes ]; then rm -f themes; fi
          if [ -e themes ] && [ ! -d themes ]; then rm -f themes; fi
          mkdir -p themes
          git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/papermod

      - name: Patch PaperMod RSS for Hugo compatibility
        run: |
          RSS_FILE="themes/papermod/layouts/_default/rss.xml"
          if [ -f "$RSS_FILE" ]; then
            echo "Patching $RSS_FILE"
            sed -i 's/LanguageCode/Lang/g' "$RSS_FILE" || true
          else
            echo "$RSS_FILE not found — skipping patch"
          fi

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'

      - name: Build
        run: hugo -D

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
